packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@types/node': ^24
  create-sp: ^0.0.8
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core@0.2.8'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.2.8'
  - '@voidzero-dev/vite-plus-darwin-x64@0.2.8'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.8'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.8'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.8'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.8'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.8'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.8'
  - vite-plus@0.2.8
  - '@vue/compiler-core@3.5.41'
  - '@vue/compiler-dom@3.5.41'
  - '@vue/compiler-sfc@3.5.41'
  - '@vue/compiler-ssr@3.5.41'
  - '@vue/reactivity@3.5.41'
  - '@vue/runtime-core@3.5.41'
  - '@vue/runtime-dom@3.5.41'
  - '@vue/server-renderer@3.5.41'
  - '@vue/shared@3.5.41'
  - vue@3.5.41
  - create-sp@0.0.5 || 0.0.6 || 0.0.7 || 0.0.8

allowBuilds:
  '@pnp/sp': true
